# Group Locations

## Location collection [/api/locations]

### Fetch multiple locations [GET]

+ Response 200 (application/json)

        {
            "1": {
                "id": "1",
                "label": "Atlanta",
                "email": "",
                "timezone": "America/New_York",
                "timezone_offset": -14400
            },
            "2": {
                "id": "2",
                "label": "Boston",
                "email": "",
                "timezone": "America/New_York",
                "timezone_offset": -14400
            },
            "3": {
                "id": "3",
                "label": "Chicago",
                "email": "",
                "timezone": "America/Chicago",
                "timezone_offset": -18000
            },
            "4": {
                "id": "4",
                "label": "Dallas",
                "email": "",
                "timezone": "America/Chicago",
                "timezone_offset": -18000
            },
            "5": {
                "id": "5",
                "label": "Denver",
                "email": "",
                "timezone": "America/Denver",
                "timezone_offset": -21600
            },
            "6": {
                "id": "6",
                "label": "Houston",
                "email": "",
                "timezone": "America/Chicago",
                "timezone_offset": -18000
            },
            "7": {
                "id": "7",
                "label": "Los Angeles",
                "email": "",
                "timezone": "America/Los_Angeles",
                "timezone_offset": -25200
            },
            "8": {
                "id": "8",
                "label": "New York",
                "email": "",
                "timezone": "America/New_York",
                "timezone_offset": -14400
            },
            "9": {
                "id": "9",
                "label": "San Francisco",
                "email": "",
                "timezone": "America/Los_Angeles",
                "timezone_offset": -25200
            },
            "10": {
                "id": "10",
                "label": "Seattle",
                "email": "",
                "timezone": "America/Los_Angeles",
                "timezone_offset": -25200
            },
            "11": {
                "id": "11",
                "label": "Washington, D. C.",
                "email": "",
                "timezone": "America/New_York",
                "timezone_offset": -14400
            }
        }
